package:
  name: mule
  version: "0.1.0"

source:
  git_url: git@github.com:Carroll105/MULE.git
  git_tag: v0.1.0

build:
  noarch: python
  script: |
    python -m pip install . 
    # python -m pip install scanpy==1.9.2 geomstats==2.5.0  

requirements:
  host:
    - python >=3.10
    - setuptools >=40.8
    - pip
  run:
    - python >=3.10
    # - numpy >=1.24.3
    # - pandas >=1.3.5
    # - scikit-learn >=1.2.2
    # - scanpy >=1.9.2  
    # - geomstats >=2.5.0

test:
  imports:
    - mule  

about:
  home: https://github.com/Carroll105/MULE
  license: MIT
  summary: "MULE:Mutual Exclusion in scRNA-seq"
  description: |
    MULE (Mutual Exclusion in scRNA-seq) is a tool for detecting mutually exclusive gene expression patterns in single-cell RNA-seq and spatial transcriptomics data.

extra:
  recipe-maintainers:
    - Carroll105
